### ISSUE TITLE
Loss function报错

### ISSUE THREAD

**Issue by yihjian** [bubbliiiing/yolo3-keras#10]
我把input改成有三个class的customized dataset，然后修改了部分代码迁移到tf2.0，具体改动如下：
```
1. from keras.layers import修改为from tensorflow.keras.layers import
2. 移除train.py中的tf.config和tf.session移除
3. loss.py中line 148修改为tf.while_loop
```
代码能够顺利compile，在第一次model.compile时报错，报错如下:
```
Traceback (most recent call last):
  File "f:/RM/yolo3-keras/train.py", line 206, in <module>
    'yolo_loss': lambda y_true, y_pred: y_pred})
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 446, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1592, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1652, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\keras\losses.py", line 220, in call
    y_pred, y_true)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\ops\losses\util.py", line 79, in squeeze_or_expand_dimensions
    is_last_dim_1 = math_ops.equal(1, array_ops.shape(y_pred)[-1])
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 898, in _slice_helper
    name=name)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1064, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 9535, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1786, in __init__
    control_input_ops)
  File "C:\Users\jiany\.conda\envs\deep_stock\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index -1 of dimension 0 out of bounds. for 'loss/yolo_loss_loss/strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, i
```
我怀疑是```loss.py```的line 153 expand dim出的问题，但是不熟悉customized loss不太会debug，希望作者大大解答

**Comment by bubbliiiing** [comment]
不用怀疑原来的loss，没错，你可以看看我改的tf2-yolo4，除了主干网络其它和yolo3一摸一样

**Comment by bubbliiiing** [comment]
loss里面只需要改一点点地方

**Comment by yihjian** [comment]
> 
> 
> loss里面只需要改一点点地方

我看了tf2-yolo4的repo，刨去label smoothing的部分，我看yolo4的loss改的地方只有37/38行改了```[...,::-1]```, 然后154行改了tf2.0的api，我改完报错依然一样，不知道是不是哪里疏忽了

**Comment by yihjian** [comment]
Fixed，```yolo_loss```最后一行缺少了一个```expand_dims```
