### ISSUE TITLE
训练报错问题

### ISSUE THREAD

**Issue by liminghe-li** [bubbliiiing/yolo3-keras#32]
您好大大，我训练的时候报错了这个，求帮助~
Freeze the first 184 layers of total 252 layers.
Train on 7 samples, val on 0 samples, with batch size 8.
Epoch 1/50
Traceback (most recent call last):
  File "/Users/liminghe/yolo3-keras/train.py", line 312, in <module>
    callbacks=[logging, checkpoint, reduce_lr, early_stopping])
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/keras/engine/training.py", line 2244, in fit_generator
    max_queue_size=max_queue_size)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/keras/engine/training.py", line 2362, in evaluate_generator
    generator_output = next(output_generator)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/Users/liminghe/.virtualenvs/pytorch/lib/python3.7/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/Users/liminghe/yolo3-keras/train.py", line 49, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=random)
IndexError: list index out of range

Process finished with exit code 1
————————————————————————————————————
我设置的classes是：classes = ["perf", "icon"]
图片数量7

**Comment by bubbliiiing** [comment]
图片数量过少
