### ISSUE TITLE
一直报错以为什么

### ISSUE THREAD

**Issue by youquderen97** [bubbliiiing/yolo3-keras#47]
求助：一直报错这个因为什么呀
D:\Aanconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Aanconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Aanconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Aanconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Aanconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Aanconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "d:/yolo3/predict.py", line 11, in <module>
    from yolo import YOLO
  File "d:\yolo3\yolo.py", line 9, in <module>
    from nets.yolo import yolo_body
  File "D:\Aanconda\envs\tensorflow\lib\site-packages\nets\__init__.py", line 5, in <module> 
    from nets.autograd import Hook, Parameter
  File "D:\Aanconda\envs\tensorflow\lib\site-packages\nets\autograd\__init__.py", line 3, in 
<module>
    from .functional import *
  File "D:\Aanconda\envs\tensorflow\lib\site-packages\nets\autograd\functional.py", line 15, 
in <module>
    import nets.autograd.function as fc
AttributeError: module 'nets' has no attribute 'autograd'

**Comment by youquderen97** [comment]
之前的模型都没有问题，下载了更新的之后一直报这个错误，是什么原因呀

**Comment by bubbliiiing** [comment]
你莫非装了一个nets库？一般是环境里面不小心装了啥

**Comment by youquderen97** [comment]
嘿嘿嘿 谢谢up主回复，确实是装了一个nets库。
另外我想问一下如果只训练三种类型的故障的话，我只有300张图片够吗？

**Comment by bubbliiiing** [comment]
勉强吧
